version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
      - .redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    command:
      - /usr/local/etc/redis/redis.conf
    links: 
      - redis-commander

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8088:8081" 
